### ISSUE TITLE
Genetic Analyzer is not linked to the R&D Console

### ISSUE THREAD

**Issue by ApplePlastic** [Liberty-Landing/Liberty-Station-13#211] opened 2023-05-02 06:34 UTC
Self-explanatory. Genetic analyzer isn't linked to the R&D console, so points are wasted and sent to the void if you press the sync button.

**Comment by Dissentbay** [comment] 2023-05-02 18:54
apparently you have to use a science tool on the analyzer, according to code that is
https://github.com/Liberty-Landing/Liberty-Station-13/blob/master/code/modules/genetics/machinery/genetics_analyzer.dm
line 108 fowards

sync stats at line 232, and does not send the data directly to the console, it only checks if it exists, then stores the raw data and the new mutations so you don't get points from the same mutations over and over

**Comment by ApplePlastic** [comment] 2023-05-03 05:44
Science tool states that zero points were gathered when you use it. You still get the points, though, but it easy for a new player to not realize this. 

Closing this in a little.

**Comment by Dissentbay** [comment] 2023-05-03 11:03
guess the issue is not warning the player how many points were transferred, which is fair

**Closed** 2023-05-04 21:00 UTC
